= Improved UPS for Raspberry Pi

This based on the UPS documented at http://homediyelectronics.com/projects/raspberrypi/ups/ but uses only 4 AAA NiMh cells and is charged from the Pi +5V pins.

Ensure that the cells are charged before fitting, the charge current is very low, 50mA, and a charge from flat will take a very long time.

==Operation

The Raspberry pi PSU seems to output 5.1 volts and a fully charger NiMh pack of four is 4.8V, which is *just* about enough to power the Pi for a few minutes.  A few minutes is all we need to get safe shut-down when the main power is removed.

The "powered" signal is held LOW by Q1 being turned on by the main power.  When power is lost the Battery power is sufficient to power the pi but the voltage is too low to hold Q1 ON so the voltage on the collector rises, turning ON Q3.  This signals the Pi firmware that it is running on battereis and should shut down after a short period.  The short wait is to allow for very short glitches in the power.

The voltage at the base of Q1 is determined by D2 a 3V zener and the voltage divider R4-R5.  The small difference between the 5V power supply and battery means that getting the base voltage correct is critical to the operation of the device.  The 3V zener should be considered to be a reliable device, the forward voltage of the LED may vary by device.  It would be possible to adjust the base voltage with a pot, perhaps replacing R4 and R5 with a 10K multi turn cermet trimmer. Or and additional 500R trimmer if a single pot is too course an adjustment.
