= Improved UPS for Raspberry Pi

This based on the UPS documented at http://homediyelectronics.com/projects/raspberrypi/ups/ but now uses only 2 LiPo cells.

The charge circuit is based on https://ethcircuits.com/simple-li-ion-battery-charger-circuit-diagram/

This is not a microcontroller version, only in part because of the shortage of AtTiny85 controllers.

Ensure that the cells are charged before fitting, the charge current is 80mA, and a charge from flat will take a long time.



== Building Version 3

Refer to release note for component changes.

- Do not fit D9
- Do not fit D14, short it with a link.
- Cut track between bottom of R5 and D7. Insert a 1N4148 here with stripe away from R5.
- Replace R14, R15 with a single 2K7 resistor.
- Don't fit the Molex connectors for the batteries unless you really want to.
- Solder D7 before D5 as this blocks access.
- Before fitting the buck converter on the bottom side add some Kapton-like tape the the area to add some more insulation.
- Use a leaded 1n4148 for D9 by bending the leads back to fit on the SMD pads.
- Not all of the 40 pin header pins are used. Populate as appropriate with SIL headers.
- Battery connectors are unmarked, (FFS). Connect both batteries black(-) down, red(+) up, relative to board bottom edge.
- The orientation of zener diodes D12 and D4 is missing off the board. D12 stripe up, D4 stripe down when the 40 way connector is up.

MOSFET mod

- Solder pin 1,2 and 3 to the relay hole, second from the right top row. Remove resist from the vertical part of the track to enable this.
- Solder the 10K pull-up underside from that pin to the bottom right relay pin-hole and leave this lead uncut.
- Bend that lead to pin 4 for the MOSFET.
- Wire pin 5,6,7 an 8 from the MOSFET to the buck converter input. Leave this wire long to go through th buck-converter board. Use a cut off resistor lead for this.
- If needed, super glue the MOSFET to the board.
- Use the relay holes to fit a 10K resistor underneath and diagonally and leave one leg long to connect to the MOSFET.


== Operation

The LiPo packs used in this PCB only need about enough capacity to power the Pi for a few minutes, but that is all we need to get a safe shut-down when the main power is removed.

The "powered" signal is held LOW by Q1 being turned on by the main power.
When power is lost the Battery power is sufficient to power the pi but the voltage is too low to hold Q1 ON so the voltage on the collector rises, turning ON Q3.
This signals the Pi firmware that it is running on batteries and should shut down after a short period.
The short wait is to allow for very short glitches in the power.

The voltage at the base of Q1 is determined by D3 a 5V1 zener and the voltage divider R1-R2.
The 5V1 zener should be considered to be a reliable device, the forward voltage of the LED may vary by device.



== Charging Circuit Operation

The original reference trickle charges NiMh batteries.
Converting this to LiPo presents some challenges in that LiPo battereies have a completely different charging profile.
LiPo's should normally be charged at 1/100 their capacity in mAh.
For the cells used here, 120mAh, we should charge at a max 120mA.
The charge current is set with R3, (6r6) which gives a current of 80mA.
The voltage across R6 controls the base voltage of Q5 which in turn limits the current.
The current through R6 is the set charging current.
If current rises, so does the base voltage, which tursn on Q5 and lowers the ADJ voltage on U3.
This limits the current through U3 and so the feedback loop regulates the current.
The max voltage is set with R5, R14+R15 which should give a voltage of 8V.
Charging stops at 8V even though the cells have protection that would limit this anyway.

The zener and serial diode across each cell should permit the other cell to receive charge when the adjacent cell's voltage limit circuit has cut off.
Otherwise once one cell has cut off the other cannot charge further and so my lead to cell voltage imbalance.
